apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-app.fullname" . }}-svc
spec:
  type: LoadBalancer
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

