name: CI - Lint Helm Chart

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  helm-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Lint Helm chart
        run: helm lint charts/demo-app

